### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by ChipWolf** [Ra5tko/Pokemon-Go-Ban-Check#3]
This tool is pretty useful, but there's a few oversights/issues;

- There's no need for a GUI, a command line tool is more than sufficient and will also allow for scripting.
- No multiple account support; some of us run tools which require many accounts, testing them one by one would be a process that'd take hours.
- VB.NET isn't the best language to base this kind of tool from; if it could be compiled down to a single file .exe without supplementary libraries and command-line functionality, we're in business.

Thanks!

**Comment by Ra5tko** [comment]
Thanks a lot for your valuable feedback!
Oversights/issues have been fixed and I would be glad to hear your feedback again.
